# Generated by Django 6.0 on 2025-12-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_company_id_alter_subscriptionplan_id_and_more'),
        ('policies', '0002_alter_policy_id_alter_policyacknowledgement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyaudience',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.companygroup'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='groups',
            field=models.ManyToManyField(related_name='policies', through='policies.PolicyAudience', to='account.companygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='policyaudience',
            unique_together={('policy', 'group')},
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
